name: core-identity

on:
  workflow_call:
    secrets:
      ARM_SUBSCRIPTION_ID: { required: true }
      ARM_TENANT_ID:       { required: true }
      ARM_CLIENT_ID:       { required: true }
      ARM_CLIENT_SECRET:   { required: true }
      ARM_OBJECT_ID:       { required: true }
      AZURE_CREDENTIALS:   { required: true }

permissions:
  contents: read
  id-token: write
  actions: write  # precisa para upload de artifact

jobs:
  Deployment-Core-Ecosystem:
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:           ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:     ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_bootstrap_spn_object_id: ${{ secrets.ARM_OBJECT_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ViniciusOtoni/sunny-data
          ref: main

      - name: Azure Login (bootstrap)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # backend LOCAL 
      - name: Terraform Init (local)
        run: terraform -chdir=core-identity init

      - name: Terraform Apply (core-identity)
        run: terraform -chdir=core-identity apply -auto-approve

      # disponibiliza o tfstate para o PRÓXIMO micro baixar no MESMO run
      - name: Upload Terraform state (core-identity)
        uses: actions/upload-artifact@v4
        with:
          name: tfstate-core
          path: core-identity/terraform.tfstate
