name: landing-zone
on:
  workflow_run:
    workflows: ["core-identity"]   # dispara após o workflow anterior
    types: [completed]

# Ler artefato do run anterior
permissions:
  contents: read
  id-token: write
  actions: read                   

jobs:
  Migration-Terraform-Backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Valida de o workflow anterior foi finalizado com sucesso
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:        ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:  ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v4

    # Recriando a pasta do tfsate através do valor recuperado no artefato
    - name: Download core-identity state
      uses: dawidd6/action-download-artifact@v3
      with:
          workflow: core-identity
          run_id:  ${{ github.event.workflow_run.id }}
          name: tfstate-core
          path: core-identity 

    - name: Azure Login (SPN bootstrap)
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6         

    # 1) Init / Apply usando backend local
    - name: Terraform Init (local)
      run: terraform -chdir=landing-zone init

    - name: Terraform Apply (create SA & container)
      run: terraform -chdir=landing-zone apply -auto-approve

   
    # 2) Captura outputs – nome do Storage Account e RG
    - name: Read outputs
      id: tfout
      run: |
        SA=$(terraform -chdir=landing-zone output -raw state_sa_name)
        RG=$(terraform -chdir=landing-zone output -raw state_rg_name)
        echo "sa=$SA" >> $GITHUB_OUTPUT
        echo "rg=$RG" >> $GITHUB_OUTPUT

    # 3) Re-init apontando para o backend remoto e migra o tfstate
    - name: Migrate state to Azure blob
      run: |
        terraform -chdir=landing-zone init \
          -backend-config="storage_account_name=${{ steps.tfout.outputs.sa }}" \
          -backend-config="container_name=tfstate-landing" \
          -backend-config="resource_group_name=${{ steps.tfout.outputs.rg }}" \
          -backend-config="key=landing.tfstate" \
          -migrate-state -reconfigure

    # 4) cria container tfstate-core (CLI)
    - name: Create container tfstate-core in Storage Account
      run: |
        az storage container create \
          --name tfstate-core \
          --account-name ${{ steps.tfout.outputs.sa }} \
          --auth-mode login

    # 5) migra o tfstate do core-identity para o mesmo Storage Account
    - name: Migrate core state to Storage Account
      run: |
        terraform -chdir=core-identity init \
          -backend-config="storage_account_name=${{ steps.tfout.outputs.sa }}" \
          -backend-config="container_name=tfstate-core" \
          -backend-config="resource_group_name=${{ steps.tfout.outputs.rg }}" \
          -backend-config="key=core.tfstate" \
          -migrate-state -reconfigure
