name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  create-spn:
    name: Create SPN
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:           ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:     ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Plan SPN
        run: |
          cd infra
          terraform init
          terraform plan -target=module.service_principal -out=spnplan

      - name: Apply SPN
        run: |
          cd infra
          terraform apply -auto-approve spnplan

      - name: Capture SPN outputs
        id: capture
        run: |
          cd infra
          # captura e mascara o secret
          SECRET=$(terraform output -raw spn_client_secret)
          echo "::add-mask::$SECRET"
          echo "SPN_SECRET=$SECRET" >> $GITHUB_ENV
          # captura o client_id
          ID=$(terraform output -raw spn_client_id)
          echo "SPN_ID=$ID" >> $GITHUB_ENV

      - name: Reload Env
        run: echo " » env vars reloaded"

      - name: Debug SPN Vars
        run: |
          echo "SPN ID: $SPN_ID"
          echo "SPN Secret length: ${#SPN_SECRET}"

    outputs:
      spn_client_id:     ${{ env.SPN_ID }}
      spn_client_secret: ${{ env.SPN_SECRET }}

  deploy-infra:
    name: Deploy Remaining Infra
    needs: create-spn
    runs-on: ubuntu-latest

    env:
      # credenciais admin (provider azuread.admin)
      TF_VAR_subscription_id:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:           ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:     ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # credenciais da SPN criada
      TF_VAR_spn_client_id:     ${{ needs.create-spn.outputs.spn_client_id }}
      TF_VAR_spn_client_secret: ${{ needs.create-spn.outputs.spn_client_secret }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Plan Infra
        run: |
          cd infra
          terraform init -upgrade
          terraform plan -out=infraplan

      - name: Apply Infra
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve infraplan
