name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  create-spn:
    name: Create SPN
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:       ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Plan SPN
        run: |
          cd infra
          terraform init
          terraform plan -target=module.service_principal -out=spnplan

      - name: Apply SPN
        run: |
          cd infra
          terraform apply -auto-approve spnplan

      - name: Capture SPN outputs
        id: spn
        run: |
          cd infra
          echo "spn_client_id=$(terraform output -raw spn_client_id)" >> $GITHUB_ENV
          echo "spn_client_secret=$(terraform output -raw spn_client_secret)" >> $GITHUB_ENV

      - name: Reload Env
        run: echo "Reloading environment variables for job output"

      - name: Debug SPN Vars
        run: |
          echo "spn_client_id: $spn_client_id"
          echo "spn_client_secret length: ${#spn_client_secret}"

    outputs:
      spn_client_id: ${{ env.spn_client_id }}
      spn_client_secret: ${{ env.spn_client_secret }}

  deploy-infra:
    name: Deploy Remaining Infra
    needs: create-spn
    runs-on: ubuntu-latest

    env:
      # credenciais admin (necessárias para provider azuread.admin)
      TF_VAR_subscription_id:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:           ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:     ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # credenciais da SPN criadas no job anterior
      TF_VAR_spn_client_id:     ${{ needs.create-spn.outputs.spn_client_id }}
      TF_VAR_spn_client_secret: ${{ needs.create-spn.outputs.spn_client_secret }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Plan Infra
        run: |
          cd infra
          terraform init -upgrade
          terraform plan -out=infraplan

      - name: Apply Infra
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve infraplan
