name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  bootstrap:
    name: 1️⃣ Bootstrap SPN + AKV + Store Secrets
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id:         ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:               ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:         ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret:     ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_bootstrap_spn_object_id: ${{ secrets.ARM_OBJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Apply SPN + Key Vault
        run: |
          cd infra
          terraform init
          terraform apply -target=module.service_principal -target=module.key_vault -auto-approve

  deploy-infra:
    name: 2️⃣ Deploy Infra com SPN via AKV
    needs: bootstrap
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id:         ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:               ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:         ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret:     ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_bootstrap_spn_object_id: ${{ secrets.ARM_OBJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Login com Azure CLI (SPN Bootstrap)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.ARM_CLIENT_ID }}
          tenant-id:       ${{ secrets.ARM_TENANT_ID }}
          client-secret:   ${{ secrets.ARM_CLIENT_SECRET }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Buscar SPN do AKV e autenticar como SPN dinâmica
        id: get_secrets
        run: |
          echo "🔐 Buscando secrets do Key Vault..."
          AKV_NAME="akv-medalforge-rbac"
          SPN_ID=$(az keyvault secret show --vault-name "$AKV_NAME" --name "spn-client-id" --query "value" -o tsv)
          SPN_SECRET=$(az keyvault secret show --vault-name "$AKV_NAME" --name "spn-client-secret" --query "value" -o tsv)

          echo "::add-mask::$SPN_SECRET"
          echo "SPN_ID=$SPN_ID" >> $GITHUB_ENV
          echo "SPN_SECRET=$SPN_SECRET" >> $GITHUB_ENV

      - name: Autenticar com a SPN dinâmica (via azure/login)
        uses: azure/login@v2
        with:
          client-id:       ${{ env.SPN_ID }}
          tenant-id:       ${{ secrets.ARM_TENANT_ID }}
          client-secret:   ${{ env.SPN_SECRET }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Init & Plan Infra com SPN dinâmica
        run: |
          cd infra
          terraform init -upgrade
          terraform plan -out=infraplan

      - name: Apply Infra
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve infraplan
