name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  bootstrap:
    name: 1️⃣ Bootstrap SPN + AKV + Store Secrets
    runs-on: ubuntu-latest

    env:
      TF_VAR_SUBSCRIPTION_ID:         ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_TENANT_ID:               ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_ADMIN_CLIENT_ID:         ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_ADMIN_CLIENT_SECRET:     ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_BOOTSTRAP_SPN_OBJECT_ID: ${{ secrets.ARM_OBJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (SPN Bootstrap)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Apply SPN + Key Vault
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve \
            -target=module.service_principal \
            -target=module.key_vault

  deploy-infra:
    name: 2️⃣ Deploy Remaining Infra
    needs: bootstrap
    runs-on: ubuntu-latest

    env:
      TF_VAR_SUBSCRIPTION_ID:         ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_TENANT_ID:               ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_ADMIN_CLIENT_ID:         ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_ADMIN_CLIENT_SECRET:     ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_BOOTSTRAP_SPN_OBJECT_ID: ${{ secrets.ARM_OBJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (SPN Bootstrap)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Fetch SPN credentials from AKV
        id: get_spn
        run: |
          AKV="akv-medalforge-rbac"
          SPN_ID=$(az keyvault secret show --vault-name $AKV --name spn-client-id --query value -o tsv)
          SPN_SECRET=$(az keyvault secret show --vault-name $AKV --name spn-client-secret --query value -o tsv)
          echo "::add-mask::$SPN_SECRET"
          echo "ARM_CLIENT_ID=$SPN_ID"         >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$SPN_SECRET" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}"       >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Init & Plan Remaining Infra
        run: |
          cd infra
          terraform init -upgrade
          terraform plan -out=infraplan

      - name: Apply Remaining Infra
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve infraplan
