name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  create-spn:
    name: Create SPN
    runs-on: ubuntu-latest

    env:
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:       ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.6 }
      - name: Init & Plan SPN
        run: |
          cd infra
          terraform init
          terraform plan -target=module.service_principal -out=spnplan
      - name: Apply SPN
        run: |
          cd infra
          terraform apply -auto-approve spnplan
      - name: Capture SPN outputs
        id: spn
        run: |
          cd infra
          echo "::set-output name=client_id::$(terraform output -raw spn_client_id)"
          echo "::set-output name=client_secret::$(terraform output -raw client_secret)"

    outputs:
      spn_id: ${{ steps.spn.outputs.client_id }}
      spn_secret: ${{ steps.spn.outputs.client_secret }}

  deploy-infra:
    name: Deploy Remaining Infra
    needs: create-spn
    runs-on: ubuntu-latest

    env:
      # credenciais admin (ainda necessárias para provider azuread.admin, mesmo que não operem mais)
      TF_VAR_subscription_id:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:           ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_client_id:     ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_admin_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # **credenciais da SPN** criadas no passo anterior
      TF_VAR_spn_client_id:     ${{ needs.create-spn.outputs.spn_id }}
      TF_VAR_spn_client_secret: ${{ needs.create-spn.outputs.spn_secret }}


    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.6 }

      - name: Init & Plan Infra
        run: |
          cd infra
          terraform init -upgrade
          terraform plan -out=infraplan

      - name: Apply Infra
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve infraplan
