name: workspace-config
on:
  workflow_run:
    workflows: ["databricks-workspace"]   # dispara após workspace criado
    types: [completed]

  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  uc-setup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id:        ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_databricks_account_id: ${{ secrets.ARM_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4

      # login com SPN bootstrap
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      # pega SPN dinâmica no KV
      - name: Fetch dynamic-SPN creds
        run: |
          KV="akv-medalforge-rbac-core"
          ID=$(az keyvault secret show --vault-name $KV --name spn-client-id     -o tsv --query value)
          SC=$(az keyvault secret show --vault-name $KV --name spn-client-secret -o tsv --query value)
          echo "::add-mask::$SC"
          echo "TF_VAR_spn_client_id=$ID"     >> $GITHUB_ENV
          echo "TF_VAR_spn_client_secret=$SC" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.6 }

      - run: terraform -chdir=workspace-config init
      - run: terraform -chdir=workspace-config apply -auto-approve
